// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZSWRkjDuJsWTvcNcRtKe_UKnt17L0eg',
    appId: '1:373495449327:web:9f3c041cec92974784bd1a',
    messagingSenderId: '373495449327',
    projectId: 'recyclo-d9f1b',
    authDomain: 'recyclo-d9f1b.firebaseapp.com',
    storageBucket: 'recyclo-d9f1b.appspot.com',
    measurementId: 'G-ZJ59Z9LZM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi41_eNhw_uaqnMAkM8bpQGIPfzU3_B10',
    appId: '1:373495449327:android:8bbce59a29047fb884bd1a',
    messagingSenderId: '373495449327',
    projectId: 'recyclo-d9f1b',
    storageBucket: 'recyclo-d9f1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNt8iViWQXKyVzLb7pQY54m3nhOvPwvrg',
    appId: '1:373495449327:ios:382d79232d10ed6a84bd1a',
    messagingSenderId: '373495449327',
    projectId: 'recyclo-d9f1b',
    storageBucket: 'recyclo-d9f1b.appspot.com',
    iosBundleId: 'com.example.recyclo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNt8iViWQXKyVzLb7pQY54m3nhOvPwvrg',
    appId: '1:373495449327:ios:dc726ad3baab313f84bd1a',
    messagingSenderId: '373495449327',
    projectId: 'recyclo-d9f1b',
    storageBucket: 'recyclo-d9f1b.appspot.com',
    iosBundleId: 'com.example.recyclo.RunnerTests',
  );
}
